theme: jekyll-theme-cayman
exclude:
  - node_modules/
  - .nyc_output/
  - coverage/
  - codecov.yml
  - Gemfile
  - Gemfile.lock
  - test/
  - AUTHORS.md
  - CHANGES.md
  - CONTRIBUTING.md
  - LICENSE.md
  - package.json
show_downloads: false
